[package]
name = "sc-proof-of-time"
description = "Subspace proof of time implementation"
license = "0BSD"
version = "0.1.0"
authors = ["Rahul Subramaniyam <rahulksnv@gmail.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
ab-client-proof-of-time = { workspace = true }
ab-core-primitives = { workspace = true }
ab-proof-of-time = { workspace = true }
futures = { workspace = true }
parity-scale-codec = { workspace = true }
parking_lot = { workspace = true }
rayon = { workspace = true }
schnellru = { workspace = true }
sc-client-api = { workspace = true }
sc-network = { workspace = true }
sc-network-gossip = { workspace = true }
sp-api = { workspace = true, features = ["std"] }
sp-blockchain = { workspace = true }
sp-consensus = { workspace = true }
sp-consensus-subspace = { workspace = true, features = ["std"] }
sp-runtime = { workspace = true, features = ["std"] }
tracing = { workspace = true, features = ["std"] }
