[package]
name = "ab-sparse-merkle-tree"
description = "Sparse Merkle Tree and related data structures"
license = "0BSD"
version = "0.0.1"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

# TODO: Benches

[dependencies]
ab-blake3 = { workspace = true }
# NOTE: `blake3` is here only for `no-panic` feature
blake3 = { workspace = true, optional = true }
no-panic = { workspace = true, optional = true }

[dev-dependencies]
ab-merkle-tree = { workspace = true }
rand_core = { workspace = true }
rand_chacha = { workspace = true }

[features]
no-panic = [
    "dep:no-panic",
    # Helps with testing on CPUs without AVX512 support
    "blake3/no_avx512",
]

[lints]
workspace = true
