[package]
name = "ab-system-contract-simple-wallet-base"
description = ""
license = "0BSD"
version = "0.0.1"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

[dependencies]
ab-contracts-common = { workspace = true }
ab-contracts-io-type = { workspace = true }
ab-contracts-macros = { workspace = true }
ab-contracts-standards = { workspace = true }
ab-system-contract-state = { workspace = true }
ab-transaction = { workspace = true }
blake3 = { workspace = true }
no-panic = { workspace = true, optional = true }
schnorrkel = { workspace = true }
thiserror = { workspace = true }

[features]
guest = [
    "ab-contracts-common/guest",
    "ab-contracts-macros/guest",
    "ab-contracts-standards/guest",
]
# Enables payload builder API
payload-builder = []
# Check that code can't panic under any conditions
no-panic = [
    "dep:no-panic",
]

[lints]
workspace = true
