[package]
name = "subspace-proof-of-time"
description = "Subspace proof of time implementation"
license = "0BSD"
version = "0.1.0"
authors = ["Rahul Subramaniyam <rahulksnv@gmail.com>"]
edition = "2021"
include = [
    "/src",
    "/Cargo.toml",
]

[lib]
# Necessary for CLI options to work on benches
bench = false

[dependencies]
aes.workspace = true
subspace-core-primitives.workspace = true
thiserror.workspace = true

# This is required to for benchmark dependency features to work correctly
rand = { workspace = true, optional = true }

[dev-dependencies]
core_affinity.workspace = true
criterion.workspace = true
rand.workspace = true

[[bench]]
name = "pot"
harness = false

[[bench]]
name = "pot-compare-cpu-cores"
harness = false

[features]
default = ["std"]
std = [
    "subspace-core-primitives/std",
    "thiserror/std",
    "rand?/std",
    "rand?/std_rng",
]
