[package]
name = "ab-proof-of-space-gpu"
description = "Proof of space plotting utilities for GPU (Vulkan/Metal)"
license = "0BSD"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/build.rs",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

[dependencies]
ab-core-primitives = { workspace = true }
ab-farmer-components = { workspace = true }
anyhow = { workspace = true }
parking_lot = { workspace = true }
rayon = { workspace = true }
wgpu = { workspace = true }

[lints]
workspace = true
