[package]
name = "ab-erasure-coding"
description = "Erasure coding implementation"
license = "0BSD"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/benches",
    "/src",
    "/tests",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

[lib]
# Necessary for CLI options to work on benches
bench = false

[[bench]]
name = "erasure-coding"
harness = false

[dependencies]
reed-solomon-simd = { workspace = true }
thiserror = { workspace = true, default-features = false }

[dev-dependencies]
ab-core-primitives = { workspace = true }
chacha20 = { workspace = true, features = ["rng"] }
criterion = { workspace = true }

[lints]
workspace = true
