[package]
name = "ab-transaction"
description = ""
license = "0BSD"
version = "0.0.1"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

[dependencies]
ab-aligned-buffer = { workspace = true, optional = true }
ab-contracts-common = { workspace = true }
ab-io-type = { workspace = true }
blake3 = { workspace = true }
thiserror = { workspace = true, optional = true }

[features]
# APIs that require `alloc` crate
alloc = [
    "dep:ab-aligned-buffer",
    "dep:thiserror",
]

[lints]
workspace = true
