[package]
name = "ab-proof-of-space"
description = "Proof of space implementation based"
license = "0BSD"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

[lib]
# Necessary for CLI options to work on benches
bench = false

[dependencies]
ab-blake3 = { workspace = true }
ab-chacha8 = { workspace = true }
ab-core-primitives = { workspace = true }
chacha20 = { workspace = true, features = ["cipher"] }
derive_more = { workspace = true, features = ["full"] }
parking_lot = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
seq-macro = { workspace = true }
sha2 = { workspace = true, optional = true }
spin = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
rayon = { workspace = true }
sha2 = { workspace = true }

[[bench]]
name = "pos"
harness = false

[features]
default = []
alloc = []
std = [
    "alloc",
    "derive_more/std",
    # In no-std environment we use `spin`
    "parking_lot",
]
# Enabling this feature exposes quality search on `chiapos` module as well as enables support for K=15..=24 (by default
# only K=20 is exposed)
full-chiapos = [
    "dep:sha2",
]
parallel = [
    "alloc",
    "dep:rayon",
]

[lints]
workspace = true
