//! Compilation tests for invalid usage of the API, see `tests/ui` for individual cases

// Miri can't run the compiler
#[cfg(not(miri))]
#[test]
fn ui() {
    // TODO: `trybuild` only normalizes `OUT_DIR` paths in the old build directory layout of Cargo
    //  (`build/<crate>-<hash>/out`), errors in code generated by `build.rs` point there
    // SAFETY: This is the only test in the binary, nothing reads environment variables concurrently
    unsafe {
        std::env::set_var("__CARGO_TEMPORARY_BUILD_DIR_NEW_LAYOUT_OPT_OUT", "1");
    }

    let tests = trybuild::TestCases::new();
    tests.pass("tests/ui/pass/*.rs");
    tests.compile_fail("tests/ui/*.rs");
}
