[package]
name = "ab-riscv-interpreter"
description = "Composable and generic RISC-V interpreter"
keywords = ["riscv", "risc-v", "interpreter", "no-std"]
repository = "https://github.com/nazar-pc/abundance"
homepage = "https://github.com/nazar-pc/abundance/tree/main/crates/execution/ab-riscv-interpreter"
license = "0BSD"
version = "0.0.4"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/build.rs",
    "/Cargo.toml",
    "/CHANGELOG.md",
    "/README.md",
]
links = "ab-riscv-interpreter"

[package.metadata.docs.rs]
all-features = false

[dependencies]
ab-riscv-macros = { workspace = true, features = ["proc-macro"] }
ab-riscv-primitives = { workspace = true }
no-panic-const = { workspace = true, optional = true }
replace_with = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
ab-riscv-macros = { workspace = true, features = ["build"] }

[features]
# TODO: no-panic coverage is incomplete with the following missing:
#  * All `fn execute` methods
#  * `BasicInterpreterState::execute` method
# Check that code can't panic under any conditions
no-panic = [
    "dep:no-panic-const",
    "ab-riscv-primitives/no-panic",
]

[lints]
workspace = true
