[package]
name = "ab-example-contract-wallet"
description = ""
license = "0BSD"
version = "0.0.1"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

[lib]
# Necessary for CLI options to work on benches
bench = false

[[bench]]
name = "example-contract-wallet"
harness = false

[dependencies]
ab-contracts-common = { workspace = true }
ab-contracts-macros = { workspace = true }
ab-contracts-standards = { workspace = true }
ab-core-primitives = { workspace = true }
ab-io-type = { workspace = true }
ab-system-contract-simple-wallet-base = { workspace = true }

[dev-dependencies]
ab-executor-native = { workspace = true }
ab-system-contract-code = { workspace = true }
ab-system-contract-simple-wallet-base = { workspace = true, features = ["payload-builder"] }
criterion = { workspace = true }
schnorrkel = { workspace = true, features = ["getrandom"] }

[features]
guest = [
    "ab-contracts-common/guest",
    "ab-contracts-macros/guest",
    "ab-contracts-standards/guest",
]

[lints]
workspace = true
