[package]
name = "pallet-subspace"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Subspace Labs <admin@subspace.network>"]
edition = "2024"
license = "0BSD"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Subspace consensus pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ab-core-primitives = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
frame-support = { workspace = true }
frame-system = { workspace = true }
log = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["alloc", "derive"], optional = true }
sp-consensus-subspace = { workspace = true }
sp-runtime = { workspace = true }
subspace-runtime-primitives = { workspace = true }

[dev-dependencies]
pallet-balances = { workspace = true, features = ["std"] }
rand = { workspace = true, features = ["min_const_gen"] }
schnorrkel = { workspace = true }
sp-io = { workspace = true }
subspace-verification = { workspace = true }

[features]
default = ["std"]
serde = [
    "ab-core-primitives/serde",
    "dep:serde",
]
std = [
    "parity-scale-codec/std",
    "frame-support/std",
    "frame-system/std",
    "log/std",
    "scale-info/std",
    "serde",
    "serde/std",
    "sp-consensus-subspace/std",
    "sp-io/std",
    "sp-runtime/std",
    "subspace-runtime-primitives/std",
]
runtime-benchmarks = []
