[package]
name = "ab-client-proof-of-time"
description = "Client-side proof of time implementation"
license = "0BSD"
version = "0.0.1"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

[dependencies]
ab-core-primitives = { workspace = true, features = ["scale-codec"] }
ab-client-api = { workspace = true }
ab-proof-of-time = { workspace = true }
derive_more = { workspace = true, features = ["deref", "deref_mut"] }
futures = { workspace = true, features = ["alloc", "executor"] }
parity-scale-codec = { workspace = true, features = ["derive"] }
parking_lot = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
schnellru = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true, features = ["std"] }

[lints]
workspace = true
