[package]
name = "subspace-rpc-primitives"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
description = "RPC primitives for Subspace Network"
edition = "2024"
license = "0BSD"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
ab-core-primitives = { workspace = true, features = ["scale-codec", "serde"] }
ab-farmer-components = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
subspace-networking = { workspace = true }
subspace-verification = { workspace = true, features = ["scale-codec", "serde"] }
