//! This module defines the RISC-V instruction set instructions

pub mod rv32;
pub mod rv64;
#[cfg(test)]
mod test_utils;
#[cfg(test)]
mod tests;
pub mod utils;
pub mod v;
pub mod zawrs;
pub mod zicond;
pub mod zicsr;
pub mod zifencei;
pub mod zkr;
pub mod zvbb;
pub mod zvbc;

use crate::hart::HartConfig;
use core::any::TypeId;
use core::fmt;
use core::marker::Destruct;

/// Generic instruction
pub const trait Instruction:
    fmt::Display + fmt::Debug + [const] Destruct + Copy + Send + Sync + Sized + 'static
{
    /// Types of all implemented extensions, including this instruction itself.
    ///
    /// An inherited extension is implemented when at least one of its own instructions is present
    /// in the instruction set (otherwise it was ignored in one way or another) and the same is true
    /// for all extensions it inherits. Extensions without own instructions (like `B`) are
    /// implemented when all extensions they inherit are. So individual instructions ignored by name
    /// (like `ecall` in an instruction set without system calls) or missing due to their conditions
    /// (like `amocas.b` from `Zabha` without `Zacas`) don't exclude the extension.
    ///
    /// Note that this constant is auto-generated by the macro and usually doesn't need to be
    /// specified explicitly (and if done, will cause conflicts at compile time).
    const IMPLEMENTED_EXTENSIONS: &'static [TypeId];

    /// Instruction alignment in bytes, also known as `IALIGN`
    const ALIGNMENT: u8;

    /// Hart configuration of the implementation
    type Hart: [const] HartConfig;

    /// Try to decode a single valid instruction
    fn try_decode(instruction: u32) -> Option<Self>;

    /// Instruction size in bytes
    fn size(&self) -> u8;

    /// Checks whether this instruction implements the given extension, see
    /// [`Self::IMPLEMENTED_EXTENSIONS`] for details
    #[inline(always)]
    fn implements_extension<E>() -> bool
    where
        E: Instruction<Hart = Self::Hart>,
    {
        const {
            let mut result = false;
            // TODO: Simple `.contains()` doesn't work in `const fn` yet:
            //  https://github.com/rust-lang/rust/issues/92476
            let mut index = 0;
            while index < Self::IMPLEMENTED_EXTENSIONS.len() {
                if Self::IMPLEMENTED_EXTENSIONS[index] == TypeId::of::<E>() {
                    result = true;
                }
                index += 1;
            }

            result
        }
    }
}
