//! This module defines the RISC-V instruction set instructions

mod isa;
pub mod rv32;
pub mod rv64;
#[cfg(test)]
mod test_utils;
#[cfg(test)]
mod tests;
pub mod utils;
pub mod v;
pub mod zawrs;
pub mod zicond;
pub mod zicsr;
pub mod zifencei;
pub mod zkr;
pub mod zvbb;
pub mod zvbc;

use crate::hart::HartConfig;
use crate::instructions::isa::isa_string;
use crate::registers::general_purpose::Register;
use core::any::TypeId;
use core::cmp::Ordering;
use core::fmt;
use core::marker::Destruct;

/// Canonical order of single-letter extensions, which is also used to order multi-letter `Z`
/// extensions by their second letter, see "ISA Extension Naming Conventions" chapter of the
/// RISC-V unprivileged specification
const CANONICAL_EXTENSION_ORDER: &[u8] = b"iemafdqlcbkjtpvh";

/// Key for sorting extension names in canonical order: single-letter extensions, then `Z`
/// extensions ordered by their category (second letter), then `S` extensions and everything else,
/// extensions with the same key are sorted by name
const fn canonical_key(name: &[u8]) -> (u8, usize) {
    match *name {
        [letter] => (0, category(letter)),
        [b'z', letter, ..] => (1, category(letter)),
        [b's', ..] => (2, 0),
        _ => (3, 0),
    }
}

/// Position of a letter in canonical order, letters that are not in the list go after all others
const fn category(letter: u8) -> usize {
    let mut index = 0;
    while index < CANONICAL_EXTENSION_ORDER.len() {
        if CANONICAL_EXTENSION_ORDER[index] == letter {
            return index;
        }
        index += 1;
    }

    CANONICAL_EXTENSION_ORDER.len()
}

/// Implemented extension of an instruction set, see [`Instruction::IMPLEMENTED_EXTENSIONS`]
#[derive(Debug, Clone, Copy)]
pub struct ImplementedExtension {
    /// Type ID of the instruction enum
    pub mut(self) type_id: TypeId,
    /// ISA extensions of the instruction enum, see [`Instruction::OWN_ISA_EXTENSIONS`]
    pub mut(self) own_isa_extensions: &'static [IsaExtension],
}

impl ImplementedExtension {
    /// Create a new instance for an instruction enum
    #[inline(always)]
    pub const fn new<I>() -> Self
    where
        I: Instruction,
    {
        Self {
            type_id: TypeId::of::<I>(),
            own_isa_extensions: I::OWN_ISA_EXTENSIONS,
        }
    }
}

/// ISA extension with its version.
///
/// Extensions are ordered according to the canonical order of their names (see "ISA Extension
/// Naming Conventions" chapter of the RISC-V unprivileged specification) and then by version.
#[derive(Debug, Clone, Copy)]
#[derive_const(PartialEq, Eq)]
pub struct IsaExtension {
    /// Name of the extension as used in ISA strings, for example, `zcmp`
    pub name: &'static str,
    /// Major version of the extension
    pub major_version: u8,
    /// Minor version of the extension
    pub minor_version: u8,
}

const impl PartialOrd for IsaExtension {
    #[inline(always)]
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

const impl Ord for IsaExtension {
    #[inline]
    fn cmp(&self, other: &Self) -> Ordering {
        canonical_key(self.name.as_bytes())
            .cmp(&canonical_key(other.name.as_bytes()))
            .then(self.name.as_bytes().cmp(other.name.as_bytes()))
            .then(self.major_version.cmp(&other.major_version))
            .then(self.minor_version.cmp(&other.minor_version))
    }
}

impl IsaExtension {
    /// Create a new instance
    #[inline(always)]
    pub const fn new(name: &'static str, major_version: u8, minor_version: u8) -> Self {
        Self {
            name,
            major_version,
            minor_version,
        }
    }
}

/// Generic instruction
pub const trait Instruction:
    fmt::Display + fmt::Debug + [const] Destruct + Copy + Send + Sync + Sized + 'static
{
    /// All implemented extensions, including this instruction itself, with their ISA extensions.
    ///
    /// An inherited extension is implemented when at least one of its own instructions is present
    /// in the instruction set (otherwise it was ignored in one way or another) and the same is true
    /// for all extensions it inherits. Extensions without own instructions (like `B`) are
    /// implemented when all extensions they inherit are. So individual instructions ignored by name
    /// (like `ecall` in an instruction set without system calls) or missing due to their conditions
    /// (like `amocas.b` from `Zabha` without `Zacas`) don't exclude the extension.
    ///
    /// Note that this constant is auto-generated by the macro and usually doesn't need to be
    /// specified explicitly (and if done, will cause conflicts at compile time).
    const IMPLEMENTED_EXTENSIONS: &'static [ImplementedExtension];

    /// ISA extensions defined by this instruction enum itself, without inherited ones.
    ///
    /// Empty for instruction enums that are not extensions on their own, like a collection of
    /// instructions shared by multiple extensions. Can also contain extensions implied by this
    /// instruction enum that are not modeled as instruction enums, like `zvl*b` for vector
    /// extensions.
    ///
    /// Unsupported hart configuration results in a compilation error when this constant is used.
    const OWN_ISA_EXTENSIONS: &'static [IsaExtension];

    /// ISA string as used in the `Tag_RISCV_arch` attribute of ELF files, for example,
    /// `rv64i2p1_m2p0_zmmul1p0`.
    ///
    /// Contains ISA extensions of all implemented extensions (see [`Self::IMPLEMENTED_EXTENSIONS`])
    /// in canonical order without duplicates. Only an instruction set with a base ISA (`i` or `e`)
    /// has the `rv32`/`rv64` prefix, for others it only lists extensions, like `m2p0_zmmul1p0`.
    ///
    /// Note that this constant is not supposed to be specified explicitly.
    // TODO: Make it `final` once supported:
    //  https://internals.rust-lang.org/t/final-associated-constants/24655?u=nazar-pc
    const ISA_STRING: &'static str = const {
        isa_string(
            <Self::Hart as HartConfig>::Reg::XLEN,
            Self::IMPLEMENTED_EXTENSIONS,
        )
    }
    .unsize()
    .as_str();

    /// Instruction alignment in bytes, also known as `IALIGN`
    const ALIGNMENT: u8;

    /// Hart configuration of the implementation
    type Hart: [const] HartConfig;

    /// Try to decode a single valid instruction
    fn try_decode(instruction: u32) -> Option<Self>;

    /// Instruction size in bytes
    fn size(&self) -> u8;

    /// Checks whether this instruction implements the given extension, see
    /// [`Self::IMPLEMENTED_EXTENSIONS`] for details
    #[inline(always)]
    fn implements_extension<E>() -> bool
    where
        E: Instruction<Hart = Self::Hart>,
    {
        const {
            let mut implemented_extensions = Self::IMPLEMENTED_EXTENSIONS;
            let mut result = false;
            while let [implemented_extension, rest @ ..] = implemented_extensions {
                implemented_extensions = rest;
                if implemented_extension.type_id == TypeId::of::<E>() {
                    result = true;
                }
            }

            result
        }
    }
}
