//! This module defines the RISC-V instruction set instructions

pub mod rv32;
pub mod rv64;
#[cfg(test)]
mod test_utils;
pub mod utils;
pub mod v;
pub mod zawrs;
pub mod zicond;
pub mod zicsr;
pub mod zvbb;
pub mod zvbc;

use crate::registers::general_purpose::Register;
use core::any::TypeId;
use core::fmt;
use core::marker::Destruct;

/// Generic instruction
pub const trait Instruction:
    fmt::Display + fmt::Debug + [const] Destruct + Copy + Send + Sync + Sized + 'static
{
    /// Types of all fully implemented extensions.
    ///
    /// Note that this constant is auto-generated by the macro and usually doesn't need to be
    /// specified explicitly (and if done, will cause conflicts at compile time).
    const IMPLEMENTED_EXTENSIONS: &'static [TypeId];

    /// A register type used by the instruction
    type Reg: [const] Register;

    /// Try to decode a single valid instruction
    fn try_decode(instruction: u32) -> Option<Self>;

    /// Instruction alignment in bytes
    fn alignment() -> u8;

    /// Instruction size in bytes
    fn size(&self) -> u8;

    /// Checks whether this instruction implements the given extension
    #[inline(always)]
    fn implements_extension<E>() -> bool
    where
        E: Instruction<Reg = Self::Reg>,
    {
        const {
            let mut result = false;
            // TODO: Simple `.contains()` doesn't work in `const fn` yet:
            //  https://github.com/rust-lang/rust/issues/92476
            let mut index = 0;
            while index < Self::IMPLEMENTED_EXTENSIONS.len() {
                if Self::IMPLEMENTED_EXTENSIONS[index] == TypeId::of::<E>() {
                    result = true;
                }
                index += 1;
            }

            result
        }
    }
}
