[package]
name = "ab-networking"
description = "Networking functionality for Abundance, primarily used for DSN (Distributed Storage Network)"
license = "0BSD"
version = "0.1.0"
authors = [
    "Nazar Mokrynskyi <nazar@mokrynskyi.com>",
    "Shamil Gadelshin <shamilgadelshin@gmail.com>"
]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
multihash = { version = "0.19.5", features = ["scale-codec"] }
nohash-hasher = { version = "0.2.0" }
parity-scale-codec = { version = "3.7.5", features = ["std"] }
parking_lot = { version = "0.12.5" }
pin-project = { version = "1.1.13" }
prometheus-client = { version = "0.25.0" }
rand = { version = "0.10.2", features = ["thread_rng"] }
schnellru = { version = "0.2.4" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151" }
thiserror = { version = "2.0.19" }
tokio = { version = "1.53.1", features = ["macros", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tokio-stream = { version = "0.1.19" }
tracing = { version = "0.1.44" }
unsigned-varint = { version = "0.8.0", features = ["futures", "asynchronous_codec"] }
void = { version = "1.0.2" }
libp2p = { version = "0.56.0", features = ["autonat", "dns", "gossipsub", "identify", "kad", "macros", "metrics", "noise", "ping", "plaintext", "request-response", "serde", "tcp", "tokio", "yamux"] }

[lints]
workspace = true
