[workspace]

[package]
name = "ab-proof-of-space-gpu"
description = "Proof of space plotting utilities for GPU (Vulkan/Metal)"
license = "0BSD"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true

[lib]
# SPIR-V target requires `dylib`
crate-type = ["dylib", "lib"]
path = "../src/lib.rs"

[dependencies]
ab-chacha8 = { path = "../../../../crates/shared/ab-chacha8" }
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu", rev = "f58374079a72ee1f73bf2a9bdaed435b5e44e20e" }
