[package]
name = "subspace-farmer-components"
description = "Farmer for the Subspace Network Blockchain"
license = "0BSD"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

[lib]
# Necessary for CLI options to work on benches
bench = false

[[bench]]
name = "plotting"
harness = false

[[bench]]
name = "reading"
harness = false

[[bench]]
name = "auditing"
harness = false

[[bench]]
name = "proving"
harness = false

[dependencies]
ab-archiving = { workspace = true, features = ["parallel"] }
ab-core-primitives = { workspace = true, features = ["parallel"] }
ab-erasure-coding = { workspace = true }
ab-merkle-tree = { workspace = true, features = ["alloc"] }
anyhow = { workspace = true }
async-lock = { workspace = true }
backoff = { workspace = true, features = ["futures", "tokio"] }
bitvec = { workspace = true }
fs2 = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
libc = { workspace = true }
parity-scale-codec = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true, features = ["derive"] }
static_assertions = { workspace = true }
subspace-data-retrieval = { workspace = true }
subspace-proof-of-space = { workspace = true, features = ["parallel"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "parking_lot", "rt-multi-thread", "signal", "sync"] }
tracing = { workspace = true }

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[dev-dependencies]
criterion = { workspace = true }
futures = { workspace = true }
subspace-proof-of-space = { workspace = true }
