[package]
name = "domain-block-builder"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate block builder"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
hash-db.workspace = true
sc-client-api.workspace = true
sp-api.workspace = true
sp-blockchain.workspace = true
sp-block-builder = { workspace = true, features = ["std"] }
sp-core.workspace = true
sp-externalities.workspace = true
sp-inherents.workspace = true
sp-runtime.workspace = true
sp-state-machine.workspace = true
tracing.workspace = true
