[package]
name = "ab-cli-utils"
description = "Utilities used in various CLI applications"
license = "0BSD"
version = "0.0.1"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
