use crate::metadata::IoTypeMetadataKind;

#[test]
fn check_repr() {
    let known_variants = [
        (IoTypeMetadataKind::Unit, 0),
        (IoTypeMetadataKind::Bool, 1),
        (IoTypeMetadataKind::U8, 2),
        (IoTypeMetadataKind::U16, 3),
        (IoTypeMetadataKind::U32, 4),
        (IoTypeMetadataKind::U64, 5),
        (IoTypeMetadataKind::U128, 6),
        (IoTypeMetadataKind::I8, 7),
        (IoTypeMetadataKind::I16, 8),
        (IoTypeMetadataKind::I32, 9),
        (IoTypeMetadataKind::I64, 10),
        (IoTypeMetadataKind::I128, 11),
        (IoTypeMetadataKind::Struct, 12),
        (IoTypeMetadataKind::Struct0, 13),
        (IoTypeMetadataKind::Struct1, 14),
        (IoTypeMetadataKind::Struct2, 15),
        (IoTypeMetadataKind::Struct3, 16),
        (IoTypeMetadataKind::Struct4, 17),
        (IoTypeMetadataKind::Struct5, 18),
        (IoTypeMetadataKind::Struct6, 19),
        (IoTypeMetadataKind::Struct7, 20),
        (IoTypeMetadataKind::Struct8, 21),
        (IoTypeMetadataKind::Struct9, 22),
        (IoTypeMetadataKind::Struct10, 23),
        (IoTypeMetadataKind::Struct11, 24),
        (IoTypeMetadataKind::Struct12, 25),
        (IoTypeMetadataKind::Struct13, 26),
        (IoTypeMetadataKind::Struct14, 27),
        (IoTypeMetadataKind::Struct15, 28),
        (IoTypeMetadataKind::Struct16, 29),
        (IoTypeMetadataKind::TupleStruct, 30),
        (IoTypeMetadataKind::TupleStruct1, 31),
        (IoTypeMetadataKind::TupleStruct2, 32),
        (IoTypeMetadataKind::TupleStruct3, 33),
        (IoTypeMetadataKind::TupleStruct4, 34),
        (IoTypeMetadataKind::TupleStruct5, 35),
        (IoTypeMetadataKind::TupleStruct6, 36),
        (IoTypeMetadataKind::TupleStruct7, 37),
        (IoTypeMetadataKind::TupleStruct8, 38),
        (IoTypeMetadataKind::TupleStruct9, 39),
        (IoTypeMetadataKind::TupleStruct10, 40),
        (IoTypeMetadataKind::TupleStruct11, 41),
        (IoTypeMetadataKind::TupleStruct12, 42),
        (IoTypeMetadataKind::TupleStruct13, 43),
        (IoTypeMetadataKind::TupleStruct14, 44),
        (IoTypeMetadataKind::TupleStruct15, 45),
        (IoTypeMetadataKind::TupleStruct16, 46),
        (IoTypeMetadataKind::Enum, 47),
        (IoTypeMetadataKind::Enum1, 48),
        (IoTypeMetadataKind::Enum2, 49),
        (IoTypeMetadataKind::Enum3, 50),
        (IoTypeMetadataKind::Enum4, 51),
        (IoTypeMetadataKind::Enum5, 52),
        (IoTypeMetadataKind::Enum6, 53),
        (IoTypeMetadataKind::Enum7, 54),
        (IoTypeMetadataKind::Enum8, 55),
        (IoTypeMetadataKind::Enum9, 56),
        (IoTypeMetadataKind::Enum10, 57),
        (IoTypeMetadataKind::Enum11, 58),
        (IoTypeMetadataKind::Enum12, 59),
        (IoTypeMetadataKind::Enum13, 60),
        (IoTypeMetadataKind::Enum14, 61),
        (IoTypeMetadataKind::Enum15, 62),
        (IoTypeMetadataKind::Enum16, 63),
        (IoTypeMetadataKind::EnumNoFields, 64),
        (IoTypeMetadataKind::EnumNoFields1, 65),
        (IoTypeMetadataKind::EnumNoFields2, 66),
        (IoTypeMetadataKind::EnumNoFields3, 67),
        (IoTypeMetadataKind::EnumNoFields4, 68),
        (IoTypeMetadataKind::EnumNoFields5, 69),
        (IoTypeMetadataKind::EnumNoFields6, 70),
        (IoTypeMetadataKind::EnumNoFields7, 71),
        (IoTypeMetadataKind::EnumNoFields8, 72),
        (IoTypeMetadataKind::EnumNoFields9, 73),
        (IoTypeMetadataKind::EnumNoFields10, 74),
        (IoTypeMetadataKind::EnumNoFields11, 75),
        (IoTypeMetadataKind::EnumNoFields12, 76),
        (IoTypeMetadataKind::EnumNoFields13, 77),
        (IoTypeMetadataKind::EnumNoFields14, 78),
        (IoTypeMetadataKind::EnumNoFields15, 79),
        (IoTypeMetadataKind::EnumNoFields16, 80),
        (IoTypeMetadataKind::Array8b, 81),
        (IoTypeMetadataKind::Array16b, 82),
        (IoTypeMetadataKind::Array32b, 83),
        (IoTypeMetadataKind::ArrayU8x8, 84),
        (IoTypeMetadataKind::ArrayU8x16, 85),
        (IoTypeMetadataKind::ArrayU8x32, 86),
        (IoTypeMetadataKind::ArrayU8x64, 87),
        (IoTypeMetadataKind::ArrayU8x128, 88),
        (IoTypeMetadataKind::ArrayU8x256, 89),
        (IoTypeMetadataKind::ArrayU8x512, 90),
        (IoTypeMetadataKind::ArrayU8x1024, 91),
        (IoTypeMetadataKind::ArrayU8x2028, 92),
        (IoTypeMetadataKind::ArrayU8x4096, 93),
        (IoTypeMetadataKind::VariableBytes8b, 94),
        (IoTypeMetadataKind::VariableBytes16b, 95),
        (IoTypeMetadataKind::VariableBytes32b, 96),
        (IoTypeMetadataKind::VariableBytes512, 97),
        (IoTypeMetadataKind::VariableBytes1024, 98),
        (IoTypeMetadataKind::VariableBytes2028, 99),
        (IoTypeMetadataKind::VariableBytes4096, 100),
        (IoTypeMetadataKind::VariableBytes8192, 101),
        (IoTypeMetadataKind::VariableBytes16384, 102),
        (IoTypeMetadataKind::VariableBytes32768, 103),
        (IoTypeMetadataKind::VariableBytes65536, 104),
        (IoTypeMetadataKind::VariableBytes131072, 105),
        (IoTypeMetadataKind::VariableBytes262144, 106),
        (IoTypeMetadataKind::VariableBytes524288, 107),
        (IoTypeMetadataKind::VariableBytes1048576, 108),
        (IoTypeMetadataKind::VariableBytes2097152, 109),
        (IoTypeMetadataKind::VariableBytes4194304, 110),
        (IoTypeMetadataKind::VariableBytes8388608, 111),
        (IoTypeMetadataKind::VariableBytes16777216, 112),
    ];

    for (kind, repr_byte) in known_variants {
        assert_eq!(kind as u8, repr_byte);
        assert_eq!(IoTypeMetadataKind::try_from_u8(repr_byte), Some(kind));
    }

    for byte in known_variants.len() as u8..=u8::MAX {
        assert_eq!(IoTypeMetadataKind::try_from_u8(byte), None);
    }
}
