[package]
name = "subspace-core-primitives"
description = "Core primitives for Subspace Network"
license = "0BSD"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
blake3.workspace = true
bytes = { workspace = true, optional = true }
derive_more = { workspace = true, features = ["full"] }
hex = { workspace = true }
num-traits.workspace = true
parity-scale-codec = { workspace = true, features = ["bytes", "derive", "max-encoded-len"], optional = true }
rayon = { workspace = true, optional = true }
scale-info = { workspace = true, features = ["derive"], optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde-big-array.workspace = true
static_assertions.workspace = true
uint.workspace = true

[dev-dependencies]
rand = { workspace = true, features = ["min_const_gen", "std", "std_rng"] }

[features]
alloc = [
    "dep:bytes",
    "hex/alloc",
    "serde/alloc",
]
scale-codec = [
    "dep:parity-scale-codec",
    "dep:scale-info",
    "alloc",
]
# Enables some APIs
parallel = [
    "blake3/rayon",
    "dep:rayon",
]
serde = [
    "alloc",
    "dep:serde",
    "bytes/serde",
    "hex/serde",
]
