[package]
name = "ab-riscv-benchmarks"
description = "RISC-V benchmarks"
license = "0BSD"
version = "0.0.1"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/tests",
    "/build.rs",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

[lib]
# Necessary for CLI options to work on benches
bench = false

[[bench]]
name = "riscv"
harness = false

[dependencies]
ab-blake3 = { workspace = true }
ab-contracts-macros = { workspace = true }
ab-core-primitives = { workspace = true, features = ["ed25519"] }
ab-io-type = { workspace = true }

[target.'cfg(not(target_env = "abundance"))'.dependencies]
ab-contract-file = { workspace = true }
ab-riscv-interpreter = { workspace = true, features = ["alloc"] }
ab-riscv-primitives = { workspace = true }

[dev-dependencies]
ed25519-dalek = { workspace = true }
criterion = { workspace = true }

[build-dependencies]
ab-contract-file = { workspace = true, optional = true }
ab-contracts-tooling = { workspace = true, optional = true }

[features]
default = [
    "build-contract",
]
# Enabled by default for the host, guest code disables this feature to remove build dependencies
build-contract = [
    "dep:ab-contract-file",
    "dep:ab-contracts-tooling",
]
guest = [
    "ab-contracts-macros/guest",
]

[lints]
workspace = true
