# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
unsafe = true

[highlight]
style = 'base16-snazzy'

[tableOfContents]
startLevel = 2
endLevel = 4
