name: gh-pages

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: gh-pages-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gh-pages-build:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: 'false'
          submodules: 'true'

      - name: Install mdbook with extra preprocessors
        uses: taiki-e/install-action@82cd3e7658a6f96c86c0234aeeda1748937cb0a1 # 2.85.13
        with:
          tool: d2@0.7.1,mdbook@0.5,mdbook-d2@0.3.8

      - name: Create target dir
        run: mkdir gh-pages

      - name: Build rustdoc
        run: |
          cargo -Zgitoxide -Zgit doc --locked --all --no-deps --lib --all-features
          cp -r target/doc gh-pages/rust-docs
        env:
          RUSTDOCFLAGS: -D rustdoc::broken-intra-doc-links -D rustdoc::private_intra_doc_links -Z unstable-options --enable-index-page

      - name: Install Hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # 3.2.1
        with:
          hugo-version: 0.164.0

      - name: Build main website
        run: |
          hugo build --minify --source website/main --destination $PWD/gh-pages

      - name: Build mdBook
        run: mdbook build website/book --dest-dir $PWD/gh-pages/book

      # This is needed for a custom domain to work
      - name: CNAME
        run: |
          echo "abundance.build" > gh-pages/CNAME
        if: ${{ github.repository_owner == 'nazar-pc' }}

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
        with:
          name: gh-pages
          path: gh-pages
          retention-days: 1

  gh-pages-deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-slim
    needs: gh-pages-build
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: 'false'

      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # 8.0.1
        with:
          name: gh-pages
          path: gh-pages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # 4.9.0
        with:
          branch: gh-pages
          single-commit: true
          folder: gh-pages
