[package]
name = "ab-blake3"
description = "Optimized and more exotic APIs around BLAKE3"
license = "0BSD"
version = "0.1.0"
authors = [
    "Nazar Mokrynskyi <nazar@mokrynskyi.com>",
    "Jack O'Connor <oconnor663@gmail.com>",
    "Samuel Neves",
]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

# TODO: Would be nice to have benchmarks here

[dependencies]
# NOTE: `blake3` is here only for `no-panic` feature
blake3 = { workspace = true, optional = true }
no-panic = { workspace = true, optional = true }

# TODO: Workaround for https://github.com/Rust-GPU/rust-gpu/issues/312
[target.'cfg(not(target_arch = "spirv"))'.dependencies]
blake3 = { workspace = true }

[features]
# Check that code can't panic under any conditions
no-panic = [
    "dep:no-panic",
    # Helps with testing on CPUs without AVX512 support
    "blake3?/no_avx512",
]

[lints]
workspace = true
